theme: jekyll-theme-tactile
title: Dofixed
show_downloads: "true"

github:
    zip_url: https://github.com/dofixed/dofixed-install/archive/master.zip

defaults:
  - scope:
      path: ""
    values:
      lang: "fr"
  - scope:
      path: "en"
    values:
      lang: "en"